version: '3.8'

services:
  frontend:
    build:
      context: ./interactive-pathways
      dockerfile: Dockerfile
    ports:
      - "88:8080"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:8888
      - SVG_ENDPOINT=svgconvert

  backend:
    build:
      context: ./interactive-pathways-api
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - ENV_VAR_NAME=production
      - CORS_ORIGINS=http://localhost:88
