version: '3.8'

services:
  frontend:
    build:
      context: ./interactive-pathways
      dockerfile: Dockerfile
    ports:
      - "88:8080"
    depends_on:
      - local_cors_proxy
    environment:
      - API_URL=http://localhost:8888  # Point to Nginx
      - SVG_ENDPOINT=svgconvert

  backend:
    build:
      context: ./interactive-pathways-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Backend listens on 8080 internally
    environment:
      - ENV_VAR_NAME=production

  local_cors_proxy:
    image: nginx:alpine
    ports:
      - "8888:8888"  # Nginx is exposed on 8888 externally
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
