version: '3.8'

services:
  frontend:
    build:
      context: ./interactive-pathways
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8888
        - REACT_APP_SVG_ENDPOINT=svgconvert
    ports:
      - "88:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./interactive-pathways-api
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - ENV_VAR_NAME=production
      - CORS_ORIGINS=http://localhost:88
