version: '3.8'

services:
  frontend:
    build:
      context: ./interactive-pathways
      dockerfile: Dockerfile
    ports:
      - "88:80"
    depends_on:
      - backend # Ensure backend starts first

  backend:
    build:
      context: ./interactive-pathways-api
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - ENV_VAR_NAME=production  # Add any environment variables if needed
