before_script:
    - cd api/

stages:
    - test
    - build

test_with_lab:
  stage: test
  only:
    - merge_requests
  script:
    - go test ./...

build_project:
  stage: build
  only:
    - merge_requests
  script:
    - make clean
    - make build
