steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest', './interactive-pathways-api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'interactive-pathways-api', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:latest', '--platform', 'managed', '--region', 'us-central1', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY
