runtime: static
env: standard

handlers:
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

env_variables:
  API_URL: 'https://interactive-pathways-api-6mfgpbmzzq-uc.a.run.app'
  SVG_ENDPOINT: 'svgconvert'
