steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Retrieve credentials.json from Secret Manager and save it in the appropriate location
        gcloud secrets versions access latest --secret="credentials-json" > ./interactive-pathways/tools/svgEnhancer/credentials.json

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend/frontend:latest', './interactive-pathways']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend/frontend:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'interactive-pathways',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend/frontend:latest',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
