steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend/frontend:latest', './interactive-pathways']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend/frontend:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--image-url', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend/frontend:latest', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY
